version: "3"

services:
  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_USER: adm
      MYSQL_PASSWORD: adm123
      MYSQL_DATABASE: investimento
      MYSQL_ROOT_PASSWORD: adm
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - investimento_network
    volumes:
      - db_data:/var/lib/mysql

  app:
    container_name: investimento_container
    build: .
    ports:
      - "3030:3030"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: investimento
      DB_USER: adm
      DB_PASSWORD: adm123
      AUTH_PLUGIN: mysql_native_password
    depends_on:
      - db
    networks:
      - investimento_network

networks:
  investimento_network:

volumes:
  db_data: